In [1]:
import pandas as pd
import numpy as np

# 1.1. Загрузка данных, 1.2 Выбор структуры данных для хранения информации

Зарузим данные с помощью read_csv библиотеки Pandas.

Для хранения данных будем использовать dataframe библиотеки Pandas. Он сочетает в себе удобство работы и функциональность.

In [2]:
df = pd.read_csv('brooklyn_sales_map.csv', low_memory=False)  # low_memory — 
# настройка обработки файла. Задаем False для считывание файла целиком, а не частями

In [3]:
df.shape

(390883, 111)

In [4]:
pd.set_option('display.max_columns', 111)  # для того, чтобы выводились все колонки

In [5]:
df.head()

,Unnamed: 0,borough,neighborhood,building_class_category,tax_class,block,lot,easement,building_class,address,apartment_number,zip_code,residential_units,commercial_units,total_units,land_sqft,gross_sqft,year_built,tax_class_at_sale,building_class_at_sale,sale_price,sale_date,year_of_sale,Borough,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,PolicePrct,HealthCent,HealthArea,SanitBoro,SanitDistr,SanitSub,Address,ZoneDist1,ZoneDist2,ZoneDist3,ZoneDist4,Overlay1,Overlay2,SPDist1,SPDist2,SPDist3,LtdHeight,SplitZone,BldgClass,LandUse,Easements,OwnerType,OwnerName,LotArea,BldgArea,ComArea,ResArea,OfficeArea,RetailArea,GarageArea,StrgeArea,FactryArea,OtherArea,AreaSource,NumBldgs,NumFloors,UnitsRes,UnitsTotal,LotFront,LotDepth,BldgFront,BldgDepth,Ext,ProxCode,IrrLotCode,LotType,BsmtCode,AssessLand,AssessTot,ExemptLand,ExemptTot,YearBuilt,YearAlter1,YearAlter2,HistDist,Landmark,BuiltFAR,ResidFAR,CommFAR,FacilFAR,BoroCode,BBL,CondoNo,Tract2010,XCoord,YCoord,ZoneMap,ZMCode,Sanborn,TaxMap,EDesigNum,APPBBL,APPDate,PLUTOMapID,FIRM07_FLA,PFIRM15_FL,Version,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area
0,1,3,DOWNTOWN-METROTECH,28 COMMERCIAL CONDOS,4,140,1001,NaN,R5,330 JAY STREET,COURT,11201,0,1,1,0.0,0.0,2002,4,R5,499401179.0,2008-04-23,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,3,DOWNTOWN-FULTON FERRY,29 COMMERCIAL GARAGES,4,54,1,NaN,G7,85 JAY STREET,NaN,11201,0,0,0,134988.0,0.0,0,4,G7,345000000.0,2016-12-20,2016,BK,302.0,21.00,3017.0,13.0,33.0,11201.0,L118,84.0,36.0,1000.0,3.0,2.0,1B,87 JAY STREET,M1-2/R8,NaN,NaN,NaN,NaN,NaN,MX-2,NaN,NaN,NaN,N,G7,10.0,0.0,P,85 JAY STREET BROOKLY,134988.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,490.50,275.33,0.0,0.00,NaN,0.0,N,5.0,5.0,1571850.0,1571850.0,1571850.0,1571850.0,0.0,0.0,0.0,NaN,NaN,0.00,7.20,2.0,6.5,3.0,3.000540e+09,0.0,21.0,988208.0,195011.0,12d,NaN,302 016,30101.0,NaN,3.000540e+09,12/06/2002,1.0,NaN,NaN,17V1.1,0.0,1559.889144,140131.577176
2,3,3,BROOKLYN HEIGHTS,21 OFFICE BUILDINGS,4,204,1,NaN,O6,29 COLUMBIA HEIGHTS,NaN,11201,0,0,0,32000.0,304650.0,1924,4,O6,340000000.0,2016-08-03,2016,BK,302.0,1.00,1003.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,29 COLUMBIA HEIGHTS,M2-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,O6,5.0,0.0,NaN,25-30 COLUMBIA HEIGHT,32000.0,304650.0,304650.0,0.0,264750.0,0.0,0.0,0.0,0.0,39900.0,2.0,1.0,13.0,0.0,0.0,92.42,335.92,335.0,92.00,NaN,0.0,Y,3.0,5.0,1548000.0,25463250.0,0.0,0.0,1924.0,1980.0,0.0,NaN,NaN,9.52,0.00,2.0,0.0,3.0,3.002040e+09,0.0,1.0,985952.0,195007.0,12d,NaN,302 004,30106.0,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,890.718521,34656.447240
3,4,3,MILL BASIN,22 STORE BUILDINGS,4,8470,55,NaN,K6,5120 AVENUE U,NaN,11234,0,123,123,905000.0,2548000.0,1970,4,K6,276947000.0,2012-11-28,2012,BK,318.0,698.00,2005.0,22.0,46.0,11234.0,E323,63.0,35.0,8822.0,3.0,18.0,4E,5120 AVENUE U,M3-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,K6,5.0,1.0,NaN,BROOKLYN KINGS PLAZA,905000.0,2548000.0,2548000.0,0.0,0.0,1263000.0,1285000.0,0.0,0.0,0.0,2.0,4.0,2.0,0.0,123.0,930.00,859.00,0.0,0.00,NaN,0.0,Y,3.0,5.0,36532350.0,149792400.0,0.0,0.0,1970.0,0.0,0.0,NaN,NaN,2.82,0.00,2.0,0.0,3.0,3.084700e+09,0.0,698.0,1006597.0,161424.0,23b,NaN,319 077,32502.0,NaN,0.000000e+00,NaN,1.0,1.0,1.0,17V1.1,0.0,3729.786857,797554.847834
4,5,3,BROOKLYN HEIGHTS,26 OTHER HOTELS,4,230,1,NaN,H8,21 CLARK STREET,NaN,11201,0,1,1,20267.0,356000.0,1927,4,H8,202500000.0,2017-10-31,2017,BK,302.0,3.01,2000.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,79 WILLOW STREET,R6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LH-1,N,H8,8.0,0.0,X,WATCHTOWER C/O REAL P,20267.0,356000.0,30000.0,0.0,30000.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,15.0,0.0,1.0,202.00,100.33,202.0,100.33,NaN,0.0,N,3.0,2.0,2250000.0,27166050.0,2250000.0,27166050.0,1927.0,1998.0,2000.0,Brooklyn Heights Historic District,NaN,17.57,2.43,0.0,4.8,3.0,3.002300e+09,0.0,301.0,985622.0,193713.0,12d,NaN,302 014,30106.0,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,620.761169,21360.147631

# 1.3. Предварительное выделение признаков для использования в следующих модулях

Посмотрим на датасет и в частности на количество значений NaN и решим, что с ними делать.

In [6]:
df.describe().append(df.isnull().sum().rename('isnull'))

,Unnamed: 0,borough,block,lot,easement,zip_code,residential_units,commercial_units,total_units,land_sqft,gross_sqft,year_built,tax_class_at_sale,sale_price,year_of_sale,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,PolicePrct,HealthCent,HealthArea,SanitBoro,SanitDistr,LandUse,Easements,LotArea,BldgArea,ComArea,ResArea,OfficeArea,RetailArea,GarageArea,StrgeArea,FactryArea,OtherArea,AreaSource,NumBldgs,NumFloors,UnitsRes,UnitsTotal,LotFront,LotDepth,BldgFront,BldgDepth,ProxCode,LotType,BsmtCode,AssessLand,AssessTot,ExemptLand,ExemptTot,YearBuilt,YearAlter1,YearAlter2,BuiltFAR,ResidFAR,CommFAR,FacilFAR,BoroCode,BBL,CondoNo,Tract2010,XCoord,YCoord,TaxMap,APPBBL,PLUTOMapID,FIRM07_FLA,PFIRM15_FL,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area,APPDate,Address,BldgClass,Borough,EDesigNum,Ext,FireComp,HistDist,IrrLotCode,Landmark,LtdHeight,Overlay1,Overlay2,OwnerName,OwnerType,SPDist1,SPDist2,SPDist3,Sanborn,SanitSub,SplitZone,Version,ZMCode,ZoneDist1,ZoneDist2,ZoneDist3,ZoneDist4,ZoneMap,address,apartment_number,building_class,building_class_at_sale,building_class_category,neighborhood,sale_date,tax_class
count,390883.000000,390883.0,390883.000000,390883.000000,0.0,390883.000000,390883.000000,390883.000000,390883.000000,3.908830e+05,3.908830e+05,390883.000000,390883.000000,3.908830e+05,390883.000000,303728.000000,303436.000000,302515.000000,303688.000000,303728.000000,303728.000000,303728.000000,303728.000000,303728.000000,303238.000000,303238.000000,302711.000000,303728.000000,3.037280e+05,3.037280e+05,3.037280e+05,3.037280e+05,3.037280e+05,3.037280e+05,3.037280e+05,3.037280e+05,3.037280e+05,303728.000000,303728.000000,303728.000000,303728.000000,303728.000000,303728.000000,303728.000000,303728.000000,303728.000000,303728.000000,303706.000000,303706.000000,303706.000000,3.037280e+05,3.037280e+05,3.037280e+05,3.037280e+05,303728.000000,303728.000000,303728.000000,303728.000000,303728.000000,303728.000000,303728.000000,303728.0,3.037280e+05,303728.000000,303728.000000,3.037280e+05,303728.000000,303710.000000,3.037280e+05,303728.000000,8653.0,27773.0,303728.000000,303728.000000,3.037280e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,195442.000000,3.0,4275.651169,272.509986,NaN,11208.429087,2.486138,0.174142,2.673227,2.368464e+03,2.970877e+03,1701.666307,1.642660,5.067545e+05,2009.478243,309.783211,492.221200,1971.065160,19.089803,40.888522,11207.063718,71.830012,34.460293,5758.185060,3.000326,9.776390,2.188791,0.007049,8.459416e+03,2.361238e+04,1.207292e+03,2.221657e+04,1.584349e+02,2.743297e+02,2.489965e+02,1.156844e+02,1.732853e+02,209.225606,2.086038,1.314824,3.102166,22.082923,22.347620,53.086843,109.695027,39.399567,59.381591,1.566637,4.742886,2.439326,1.209784e+05,7.813468e+05,4.136623e+04,8.105911e+04,1879.716700,295.778483,34.019662,1.662472,1.828681,0.153269,2.854437,3.0,3.045066e+09,0.029987,4715.545455,9.921077e+05,175146.073694,31396.728152,1.927884e+08,1.000145,1.0,1.0,0.000244,337.445796,8.645885e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,112838.346973,0.0,2642.765332,484.658837,NaN,361.207836,48.200178,1.653362,48.233343,2.509129e+04,1.453960e+04,636.764362,0.906378,2.353965e+06,4.504907,5.457593,331.650433,992.300369,4.221940,4.648494,382.456905,8.632760,2.514558,2576.513859,0.019130,5.455605,1.912236,0.086297,3.140562e+04,8.164505e+04,1.307823e+04,7.949109e+04,4.274347e+03,3.486221e+03,5.525525e+03,5.206794e+03,5.201557e+03,4586.906650,0.560690,2.247752,2.927788,79.764423,79.954151,99.398538,63.857962,56.369625,43.217604,1.206424,0.701608,1.559428,7.152424e+05,3.227031e+06,2.495788e+05,1.524291e+06,317.759012,710.334178,259.086380,1.549262,1.139002,0.811046,1.428735,0.0,2.571172e+07,8.840051,17545.128104,7.391759e+04,18390.569903,754.905314,7.409608e+08,0.017021,0.0,0.0,0.036740,329.587401,3.116106e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,3.0,1.000000,1.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000,0.000000e+00,2003.000000,301.000000,1.000000,1.000000,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,3.000010e+09,0.000000,0.000000,0.000000e+00,0.000000,3.000000,0.000000e+00,1.000000,1.0,1.0,0.000000,2.143758,1.007072e-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,97721.500000,3.0,1786.000000,21.000000,NaN,11209.000000,1.000000,0.000000,1.000000,0.000000e+00,0.000000e+00,1905.000000,1.000000,0.000000e+00,2005.000000,305.000000,231.000000,1002.000000,16.000000,37.000000,11209.000000,66.000000,32.000000,3500.000000,3.000000,5.000000,1.000000,0.000000,1.933000e+03,1.848000e+03,0.000000e+00,1.440000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,2.000000,1.000000,2.000000,2.000000,2.000000,20.000000,100.000000,18.750000,40.000000,0.000000,5.000000,1.000000,6.137000e+03,2.329600e+04,0.000000e+00,0.000000e+00,1910.000000,0.000000,0.000000,0.800000,0.900000,0.000000,2.000000,3.0,3.018440e+09,0.000000,246.000000,9.892368e+05,165334.750000,30611.000000,0.000000e+00,1.000000,1.0,1.0,0.000000,238.997798,1.938904e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,195442.000000,3.0,4305.000000,45.000000,NaN,11219.000000,1.000000,0.000000,1.000000,1.900000e+03,1.820000e+03,1925.000000,1.000000,2.750000e+05,2009.000000,310.000000,417.000000,2001.000000,19.000000,41.000000,11220.000000,70.000000,35.000000,6410.000000,3.000000,10.000000,2.000000,0.000000,2.252000e+03,2.688000e+03,0.000000e+00,2.172000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,2.000000,1.000000,2.000000,2.000000,2.000000,24.000000,100.000000,20.000000,50.000000,2.000000,5.000000,2.000000,9.900000e+03,3.438000e+04,0.000000e+00,0.000000e+00,1926.000000,0.000000,0.000000,1.220000,2.000000,0.000000,2.000000,3.0,3.047920e+09,0.000000,440.000000,9.975955e+05,175906.000000,31506.000000,0.000000e+00,1.000000,1.0,1.0,0.000000,249.411350,2.316886e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,293162.500000,3.0,6585.000000,94.000000,NaN,11230.000000,2.000000,0.000000,2.000000,2.500000e+03,3.000000e+03,1954.000000,2.000000,5.930000e+05,2014.000000,315.000000,702.010000,3000.000000,21.000000,45.000000,11230.000000,78.000000,37.000000,8020.000000,3.000000,15.000000,3.000000,0.000000,3.408000e+03,4.500000e+03,0.000000e+00,3.600000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,2.000000,1.000000,3.000000,4.000000,4.000000,36.000000,100.170000,25.000000,65.000000,3.000000,5.000000,4.000000,2.275100e+04,9.553500e+04,1.550000e+03,1.550000e+03,1945.000000,0.000000,0.000000,1.990000,2.430000,0.000000,4.800000,3.0,3.066810e+09,0.000000,810.000000,1.005059e+06,187140.000000,32005.000000,0.000000e+00,1.000000,1.0,1.0,0.000000,283.169119,3.478477e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,390883.000000,3.0,8955.000000,9133.000000,NaN,33803.000000,20811.000000,355.000000,20811.000000,7.446955e+06,2.548000e+06,2017.000000,4.000000,4.994012e+08,2017.000000,355.000000,1522.000000,7003.000000,32.000000,48.000000,11416.000000,94.000000,39.000000,9300.000000,5.000000,55.000000,11.000000,2.000000,7.446955e+06,2.548000e+06,2.548000e+06,1.493793e+06,1.239070e+06,1.263000e+06,1.285000e+06,1.118000e+06,1.324592e+06,846120.000000,7.000000,236.000000,119.000000,1168.000000,1168.000000,2811.000000,2285.000000,2500.000000,6517.000000,3.000000,9.000000,5.000000,6.113954e+07,5.464840e+08,6.113954e+07,5.464840e+08,2017.000000,2017.000000,2017.000000,51.780000,10.000000,12.000000,12.000000,3.0,3.089550e+09,2936.000000,118202.000000,1.024202e+06,208406.000000,32605.000000,3.089321e+09,3.000000,1.0,1.0,7.000000,19861.521019,7.149338e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
isnull,0.000000,0.0,0.000000,0.000000,390883.0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,87155.000000,87447.000000,88368.000000,87195.000000,87155.000000,87155.000000,87155.000000,87155.000000,87155.000000,87645.000000,87645.000000,88172.000000,87155.000000,8.715500e+04,8.715500e+04,8.715500e+04,8.715500e+04,8.715500e+04,8.715500e+04,8.715500e+04,8.715500e+04,8.715500e+04,87155.000000,87155.000000,87155.000000,87155.000000,87155.000000,87155.000000,87155.000000,87155.000000,87155.000000,87155.000000,87177.000000,87177.000000,87177.000000,8.715500e+04,8.715500e+04,8.715500e+04,8.715500e+04,87155.000000,87155.000000,87155.000000,87155.000000,87155.000000,87155.000000,87155.000000,87155.0,8.715500e+04,87155.000000,87155.000000,8.715500e+04,87155.000000,87173.000000,8.715500e+04,87155.000000,382230.0,363110.0,87155.000000,87155.000000,8.715500e+04,371624.0,87178.0,87177.0,87155.0,387329.0,324750.0,87403.0,371209.0,87177.0,390757.0,385762.0,348962.0,390835.0,87259.0,337389.0,355383.0,390859.0,390879.0,87173.0,87931.0,87177.0,87155.0,384771.0,87169.0,375768.0,390697.0,390880.0,87155.0,1.0,305267.0,6934.0,0.0,83.0,0.0,0.0,6934.0

Но для начала посмотрим на значения наших колонок

In [7]:
df.columns.values

array(['Unnamed: 0', 'borough', 'neighborhood', 'building_class_category',
       'tax_class', 'block', 'lot', 'easement', 'building_class',
       'address', 'apartment_number', 'zip_code', 'residential_units',
       'commercial_units', 'total_units', 'land_sqft', 'gross_sqft',
       'year_built', 'tax_class_at_sale', 'building_class_at_sale',
       'sale_price', 'sale_date', 'year_of_sale', 'Borough', 'CD',
       'CT2010', 'CB2010', 'SchoolDist', 'Council', 'ZipCode', 'FireComp',
       'PolicePrct', 'HealthCent', 'HealthArea', 'SanitBoro',
       'SanitDistr', 'SanitSub', 'Address', 'ZoneDist1', 'ZoneDist2',
       'ZoneDist3', 'ZoneDist4', 'Overlay1', 'Overlay2', 'SPDist1',
       'SPDist2', 'SPDist3', 'LtdHeight', 'SplitZone', 'BldgClass',
       'LandUse', 'Easements', 'OwnerType', 'OwnerName', 'LotArea',
       'BldgArea', 'ComArea', 'ResArea', 'OfficeArea', 'RetailArea',
       'GarageArea', 'StrgeArea', 'FactryArea', 'OtherArea', 'AreaSource',
       'NumBldgs', 'NumFloors', 'UnitsRes', 'UnitsTotal', 'LotFront',
       'LotDepth', 'BldgFront', 'BldgDepth', 'Ext', 'ProxCode',
       'IrrLotCode', 'LotType', 'BsmtCode', 'AssessLand', 'AssessTot',
       'ExemptLand', 'ExemptTot', 'YearBuilt', 'YearAlter1', 'YearAlter2',
       'HistDist', 'Landmark', 'BuiltFAR', 'ResidFAR', 'CommFAR',
       'FacilFAR', 'BoroCode', 'BBL', 'CondoNo', 'Tract2010', 'XCoord',
       'YCoord', 'ZoneMap', 'ZMCode', 'Sanborn', 'TaxMap', 'EDesigNum',
       'APPBBL', 'APPDate', 'PLUTOMapID', 'FIRM07_FLA', 'PFIRM15_FL',
       'Version', 'MAPPLUTO_F', 'SHAPE_Leng', 'SHAPE_Area'], dtype=object)

Опираясь на значения колонок и описание датасета можно смело удалить некоторые колонки. В основном мы удаляем либо те признаки, которые дублируют друг друга, либо те, которые содержат много пропусков, либо те, которые никак не сильно влиятельны.

0) 'Unnamed: 0' - это ID продажи, удаляем.
1) 'borough' & 'Borough' - это район продажи, так как датасет содержит только Бруклин, удаляем их.

In [8]:
df['Borough'].value_counts()

BK    303728
Name: Borough, dtype: int64

2) 'BldgClass' тоже самое что 'building_class'.

3) 'apartment_number' более 90% пропусков.

4) 'building_class_category' тоже самое что 'building_class'.

5) 'ZipCode' тоже самое что 'zip_code'.

6) 'YearBuilt' тоже самое что 'year_built'.

7) 'BoroCode' тоже самое что 'Borough'.

8) 'Address' тоже самое что 'address'.

9) 'easement' дублирует 'Easements'

10) 'FIRM07_FLA' более 90% пропусков.

11) 'PFIRM15_FL' более 90% пропусков.

12) 'Ext' более 80% пропусков.

13) 'HistDist' более 90% пропусков.

14) 'Landmark' более 90% пропусков.

15) 'LtdHeight' более 90% пропусков.

16) 'Overlay1' более 80% пропусков.

17) 'Overlay2' более 90% пропусков.

18) 'OwnerType' более 80% пропусков.

19) 'SPDist1' более 90% пропусков.

20) 'SPDist2' более 90% пропусков.

21) 'SPDist3' более 90% пропусков.

22) 'ZMCode' более 90% пропусков.

23) 'ZoneDist2' более 90% пропусков.

24) 'ZoneDist3' более 90% пропусков.

25) 'ZoneDist4'более 90% пропусков.

26) 'EDesigNum' более половины пропусков.

27) 'APPDate' более половины пропусков.

In [9]:
columns_to_delete = ['Unnamed: 0', 'borough', 'Borough', 'BldgClass', 'apartment_number', 'building_class_category', 'ZipCode',
                    'YearBuilt', 'BoroCode', 'Address', 'easement', 'FIRM07_FLA', 'PFIRM15_FL', 'Ext', 'HistDist', 'Landmark',
                    'LtdHeight', 'Overlay1', 'Overlay2', 'OwnerType', 'SPDist1', 'SPDist2', 'SPDist3', 'ZMCode', 'ZoneDist2',
                    'ZoneDist3', 'ZoneDist4', 'EDesigNum', 'CT2010', 'CB2010', 'AreaSource', 'UnitsRes', 'UnitsTotal', 'Tract2010',
                    'APPDate']
df.drop(columns_to_delete, inplace=True, axis=1)

In [10]:
df.columns.values

array(['neighborhood', 'tax_class', 'block', 'lot', 'building_class',
       'address', 'zip_code', 'residential_units', 'commercial_units',
       'total_units', 'land_sqft', 'gross_sqft', 'year_built',
       'tax_class_at_sale', 'building_class_at_sale', 'sale_price',
       'sale_date', 'year_of_sale', 'CD', 'SchoolDist', 'Council',
       'FireComp', 'PolicePrct', 'HealthCent', 'HealthArea', 'SanitBoro',
       'SanitDistr', 'SanitSub', 'ZoneDist1', 'SplitZone', 'LandUse',
       'Easements', 'OwnerName', 'LotArea', 'BldgArea', 'ComArea',
       'ResArea', 'OfficeArea', 'RetailArea', 'GarageArea', 'StrgeArea',
       'FactryArea', 'OtherArea', 'NumBldgs', 'NumFloors', 'LotFront',
       'LotDepth', 'BldgFront', 'BldgDepth', 'ProxCode', 'IrrLotCode',
       'LotType', 'BsmtCode', 'AssessLand', 'AssessTot', 'ExemptLand',
       'ExemptTot', 'YearAlter1', 'YearAlter2', 'BuiltFAR', 'ResidFAR',
       'CommFAR', 'FacilFAR', 'BBL', 'CondoNo', 'XCoord', 'YCoord',
       'ZoneMap', 'Sanborn', 'TaxMap', 'APPBBL', 'PLUTOMapID', 'Version',
       'MAPPLUTO_F', 'SHAPE_Leng', 'SHAPE_Area'], dtype=object)

Удалим строки с ценой продажи 0, так как скорее всего, нулевая цена продажи не связана с продажей (к тому же скорее всего sale_price окажется таргетной переменной). Также заменим NaN/0 во многих строках на медиану/моду.

In [11]:
df=df[df['sale_price'] != 0]
df['gross_sqft'] = df['gross_sqft'].replace(0.0, df['gross_sqft'].median())
df['land_sqft'] = df['land_sqft'].replace(0.0, df['land_sqft'].median())
df['NumBldgs']= df['NumBldgs'].fillna(df['NumBldgs'].median())
df['NumFloors']= df['NumFloors'].fillna(df['NumFloors'].median())
df['ProxCode']= df['ProxCode'].fillna(df['ProxCode'].mode()[0])
df['LotType']= df['LotType'].fillna(df['LotType'].mode()[0])
df['BsmtCode']= df['BsmtCode'].fillna(df['BsmtCode'].mode()[0])
df['LandUse']= df['LandUse'].fillna(df['LandUse'].mode()[0])
df['AssessLand']= df['AssessLand'].fillna(df['AssessLand'].median())
df['AssessTot']= df['AssessTot'].fillna(df['AssessTot'].median())
df['ExemptLand']= df['ExemptLand'].fillna(df['ExemptLand'].median())
df['ExemptTot']= df['ExemptTot'].fillna(df['ExemptTot'].median())
df['BuiltFAR']= df['BuiltFAR'].fillna(df['BuiltFAR'].median())
df['ResidFAR']= df['ResidFAR'].fillna(df['ResidFAR'].median())
df['CommFAR']= df['CommFAR'].fillna(df['CommFAR'].median())
df['FacilFAR']= df['FacilFAR'].fillna(df['FacilFAR'].mean())
df['OwnerName']= df['OwnerName'].fillna(value=0)
df['IrrLotCode']= df['IrrLotCode'].fillna(value=0)
df['SplitZone']= df['SplitZone'].fillna(value=0)
df['XCoord']= df['XCoord'].fillna(df['XCoord'].mode()[0])
df['YCoord']= df['YCoord'].fillna(df['YCoord'].mode()[0])
df['XCoord']= df['XCoord'].replace(0.0,df['XCoord'].mode()[0] )
df['YCoord']= df['YCoord'].replace(0.0,df['YCoord'].mode()[0] )
df['ComArea']= df['ComArea'].fillna(df['ComArea'].median())
df['ResArea']= df['ResArea'].fillna(df['ResArea'].median())
df['OfficeArea']= df['OfficeArea'].fillna(df['OfficeArea'].median())
df['RetailArea']= df['RetailArea'].fillna(df['RetailArea'].median())
df['GarageArea']= df['GarageArea'].fillna(df['GarageArea'].median())
df['OtherArea']= df['OtherArea'].fillna(df['OtherArea'].median())
df['StrgeArea']= df['StrgeArea'].fillna(df['StrgeArea'].median())
df['FactryArea']= df['FactryArea'].fillna(df['FactryArea'].median())
df['LotFront']= df['LotFront'].fillna(df['LotFront'].median())
df['LotDepth']= df['LotDepth'].fillna(df['LotDepth'].median())
df['BldgFront']= df['BldgFront'].fillna(df['BldgFront'].median())
df['BldgDepth']= df['BldgDepth'].fillna(df['BldgDepth'].median())
df['HealthArea']= df['HealthArea'].fillna(df['HealthArea'].median())
df['YearAlter1']= df['YearAlter1'].fillna(df['YearAlter1'].mode()[0])
df['YearAlter2']= df['YearAlter2'].fillna(df['YearAlter2'].mode()[0])
df['SchoolDist']= df['SchoolDist'].fillna(df['SchoolDist'].median())
df['Council']= df['Council'].fillna(df['Council'].median())
df['PolicePrct']= df['PolicePrct'].fillna(df['PolicePrct'].median())
df['HealthCent']= df['HealthCent'].fillna(df['HealthCent'].median())
df['SanitDistr']= df['SanitDistr'].fillna(df['SanitDistr'].median())
df['Easements']= df['Easements'].fillna(df['Easements'].median())
df['LotArea']= df['LotArea'].fillna(df['LotArea'].median())
df['BldgArea']= df['BldgArea'].fillna(df['BldgArea'].median())
df['BBL']= df['BBL'].fillna(df['BBL'].median())
df['CondoNo']= df['CondoNo'].fillna(df['CondoNo'].median())
df['TaxMap']= df['TaxMap'].fillna(df['TaxMap'].median())
df['APPBBL']= df['APPBBL'].fillna(df['APPBBL'].median())
df['PLUTOMapID']= df['PLUTOMapID'].fillna(df['PLUTOMapID'].median())
df['MAPPLUTO_F']= df['MAPPLUTO_F'].fillna(df['MAPPLUTO_F'].median())
df['SHAPE_Leng']= df['SHAPE_Leng'].fillna(df['SHAPE_Leng'].median())
df['SHAPE_Area']= df['SHAPE_Area'].fillna(df['SHAPE_Area'].median())

In [12]:
df.describe().append(df.isnull().sum().rename('isnull'))

,block,lot,zip_code,residential_units,commercial_units,total_units,land_sqft,gross_sqft,year_built,tax_class_at_sale,sale_price,year_of_sale,CD,SchoolDist,Council,PolicePrct,HealthCent,HealthArea,SanitBoro,SanitDistr,LandUse,Easements,LotArea,BldgArea,ComArea,ResArea,OfficeArea,RetailArea,GarageArea,StrgeArea,FactryArea,OtherArea,NumBldgs,NumFloors,LotFront,LotDepth,BldgFront,BldgDepth,ProxCode,LotType,BsmtCode,AssessLand,AssessTot,ExemptLand,ExemptTot,YearAlter1,YearAlter2,BuiltFAR,ResidFAR,CommFAR,FacilFAR,BBL,CondoNo,XCoord,YCoord,TaxMap,APPBBL,PLUTOMapID,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area,FireComp,IrrLotCode,OwnerName,Sanborn,SanitSub,SplitZone,Version,ZoneDist1,ZoneMap,address,building_class,building_class_at_sale,neighborhood,sale_date,tax_class
count,250740.000000,250740.000000,250740.000000,250740.000000,250740.000000,250740.000000,2.507400e+05,2.507400e+05,250740.000000,250740.000000,2.507400e+05,250740.000000,193052.000000,250740.000000,250740.000000,250740.000000,250740.000000,250740.000000,192955.000000,250740.000000,250740.000000,250740.000000,2.507400e+05,2.507400e+05,2.507400e+05,250740.000000,250740.000000,2.507400e+05,2.507400e+05,2.507400e+05,250740.000000,250740.000000,250740.000000,250740.000000,250740.000000,250740.000000,250740.000000,250740.000000,250740.000000,250740.000000,250740.000000,2.507400e+05,2.507400e+05,2.507400e+05,2.507400e+05,250740.000000,250740.000000,250740.000000,250740.000000,250740.000000,250740.000000,2.507400e+05,250740.000000,2.507400e+05,250740.000000,250740.000000,2.507400e+05,250740.000000,250740.000000,250740.000000,2.507400e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,4189.284649,287.706002,11207.029002,2.311307,0.129241,2.444516,2.655776e+03,3.255816e+03,1726.133589,1.593515,7.899885e+05,2009.435730,309.758480,19.081806,40.894484,71.676115,34.636919,5902.737146,3.000280,9.808642,1.857988,0.006844,8.647794e+03,2.532876e+04,9.105733e+02,24161.641844,108.428703,1.940076e+02,2.590548e+02,6.964609e+01,100.081734,152.943408,1.287222,3.114383,54.180019,110.905054,40.223913,60.038497,1.176386,4.783640,2.359025,1.253739e+05,8.220541e+05,4.379542e+04,7.301655e+04,249.415111,27.602979,1.712064,1.920840,0.109817,2.902213,3.045362e+09,0.013691,9.952781e+05,180156.628595,31413.822170,1.413278e+08,1.000120,0.000191,341.132436,8.849936e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,2678.560547,493.552514,376.904325,42.745798,1.376688,42.775222,1.061394e+04,1.326602e+04,608.719569,0.778389,2.900768e+06,4.525858,5.454068,3.765600,4.065935,7.413166,2.148875,2256.605547,0.017923,4.784269,1.567647,0.085530,2.674353e+04,8.542649e+04,1.088030e+04,83516.856107,2663.846055,3.147304e+03,5.855799e+03,4.062933e+03,3364.325266,3231.575979,2.299514,3.014334,102.613973,62.608803,57.826739,42.844592,1.247640,0.642692,1.380847,6.984964e+05,3.175447e+06,2.373455e+05,1.159624e+06,660.999653,233.765789,1.550525,1.051994,0.744694,1.278462,2.287860e+07,5.510271,1.045391e+04,13588.449679,669.057807,6.401777e+08,0.015469,0.032448,324.198421,2.690734e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,1.000000e+00,0.000000,1.000000,1.000000e+00,2003.000000,301.000000,13.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000010e+09,0.000000,9.730570e+05,147654.000000,3.000000,0.000000e+00,1.000000,0.000000,19.048751,2.393000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1666.000000,21.000000,11209.000000,1.000000,0.000000,1.000000,1.800000e+03,1.584000e+03,1907.000000,1.000000,3.000000e+05,2005.000000,305.000000,17.000000,38.000000,67.000000,33.000000,4400.000000,3.000000,6.000000,1.000000,0.000000,2.000000e+03,2.100000e+03,0.000000e+00,1692.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,1.000000,2.000000,20.000000,100.000000,20.000000,44.000000,0.000000,5.000000,2.000000,7.223000e+03,2.622400e+04,0.000000e+00,0.000000e+00,0.000000,0.000000,0.960000,1.250000,0.000000,2.000000,3.027910e+09,0.000000,9.876180e+05,168878.000000,30906.000000,0.000000e+00,1.000000,0.000000,242.443211,2.030010e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,4126.000000,46.000000,11219.000000,1.000000,0.000000,1.000000,1.800000e+03,1.584000e+03,1926.000000,1.000000,4.968600e+05,2009.000000,310.000000,19.000000,41.000000,71.000000,35.000000,6410.000000,3.000000,10.000000,1.000000,0.000000,2.342000e+03,2.760000e+03,0.000000e+00,2244.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,1.000000,2.000000,24.500000,100.000000,20.000000,50.000000,1.000000,5.000000,2.000000,1.004800e+04,3.511100e+04,0.000000e+00,0.000000e+00,0.000000,0.000000,1.300000,2.000000,0.000000,2.902213,3.047410e+09,0.000000,9.930140e+05,184407.000000,31504.000000,0.000000e+00,1.000000,0.000000,250.515969,2.372194e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,6555.000000,115.000000,11231.000000,2.000000,0.000000,2.000000,2.300000e+03,2.800000e+03,1956.000000,2.000000,7.550000e+05,2014.000000,315.000000,21.000000,44.000000,75.000000,36.000000,7520.000000,3.000000,13.000000,2.000000,0.000000,3.000000e+03,3.952250e+03,0.000000e+00,3280.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,1.000000,3.000000,30.000000,100.000000,25.000000,60.000000,2.000000,5.000000,2.000000,1.641100e+04,7.055400e+04,1.550000e+03,1.550000e+03,0.000000,0.000000,1.810000,2.430000,0.000000,3.000000,3.061220e+09,0.000000,1.002832e+06,193504.000000,31809.000000,0.000000e+00,1.000000,0.000000,270.431076,3.026932e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,8955.000000,9033.000000,11416.000000,20811.000000,355.000000,20811.000000,2.574982e+06,2.548000e+06,2017.000000,4.000000,4.994012e+08,2017.000000,355.000000,32.000000,48.000000,94.000000,39.000000,9300.000000,4.000000,55.000000,11.000000,2.000000,2.074300e+06,2.548000e+06,2.548000e+06,878265.000000,418182.000000,1.263000e+06,1.285000e+06,1.118000e+06,574055.000000,660000.000000,236.000000,119.000000,2811.000000,2285.000000,2500.000000,6517.000000,3.000000,9.000000,5.000000,6.113954e+07,5.107491e+08,6.113954e+07,5.107491e+08,2017.000000,2017.000000,51.780000,10.000000,12.000000,12.000000,3.089550e+09,2644.000000,1.024202e+06,208406.000000,32605.000000,3.089321e+09,3.000000,7.000000,19861.521019,1.560865e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
isnull,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,57688.000000,0.000000,0.000000,0.000000,0.000000,0.000000,57785.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,57713.0,0.0,0.0,57699.0,57942.0,0.0,57688.0,57699.0,57688.0,1.0,3560.0,0.0,0.0,0.0,3560.0

Категориальными и некотрыми жругими признаками займёмся позже